/* generated configuration header file - do not edit */
#ifndef SF_CRYPTO_SIGNATURE_CFG_H_
#define SF_CRYPTO_SIGNATURE_CFG_H_
#define SF_CRYPTO_SIGNATURE_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#endif /* SF_CRYPTO_SIGNATURE_CFG_H_ */
