// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 2024-06-04
// 16:57:23
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#include   "App.h"
#include   "BLE_main.h"

#define CASE_RETURN_STR(enum_val)          case enum_val: return #enum_val;

/*-----------------------------------------------------------------------------------------------------


  \param mode

  \return const char*
-----------------------------------------------------------------------------------------------------*/
const char* get_bt_advert_mode_name(wiced_bt_ble_advert_mode_t mode)
{
  switch ((int)mode)
  {
    CASE_RETURN_STR(BTM_BLE_ADVERT_OFF)
    CASE_RETURN_STR(BTM_BLE_ADVERT_DIRECTED_HIGH)
    CASE_RETURN_STR(BTM_BLE_ADVERT_DIRECTED_LOW)
    CASE_RETURN_STR(BTM_BLE_ADVERT_UNDIRECTED_HIGH)
    CASE_RETURN_STR(BTM_BLE_ADVERT_UNDIRECTED_LOW)
    CASE_RETURN_STR(BTM_BLE_ADVERT_NONCONN_HIGH)
    CASE_RETURN_STR(BTM_BLE_ADVERT_NONCONN_LOW)
    CASE_RETURN_STR(BTM_BLE_ADVERT_DISCOVERABLE_HIGH)
    CASE_RETURN_STR(BTM_BLE_ADVERT_DISCOVERABLE_LOW)
  }
  return "UNKNOWN_MODE";
}
/*-----------------------------------------------------------------------------------------------------


  \param event

  \return const char*
-----------------------------------------------------------------------------------------------------*/
const char* get_btm_event_name(wiced_bt_management_evt_t event)
{
  switch ((int)event)
  {
    CASE_RETURN_STR(BTM_ENABLED_EVT)
    CASE_RETURN_STR(BTM_DISABLED_EVT)
    CASE_RETURN_STR(BTM_POWER_MANAGEMENT_STATUS_EVT)
    CASE_RETURN_STR(BTM_PIN_REQUEST_EVT)
    CASE_RETURN_STR(BTM_USER_CONFIRMATION_REQUEST_EVT)
    CASE_RETURN_STR(BTM_PASSKEY_NOTIFICATION_EVT)
    CASE_RETURN_STR(BTM_PASSKEY_REQUEST_EVT)
    CASE_RETURN_STR(BTM_KEYPRESS_NOTIFICATION_EVT)
    CASE_RETURN_STR(BTM_PAIRING_IO_CAPABILITIES_BR_EDR_REQUEST_EVT)
    CASE_RETURN_STR(BTM_PAIRING_IO_CAPABILITIES_BR_EDR_RESPONSE_EVT)
    CASE_RETURN_STR(BTM_PAIRING_IO_CAPABILITIES_BLE_REQUEST_EVT)
    CASE_RETURN_STR(BTM_PAIRING_COMPLETE_EVT)
    CASE_RETURN_STR(BTM_ENCRYPTION_STATUS_EVT)
    CASE_RETURN_STR(BTM_SECURITY_REQUEST_EVT)
    CASE_RETURN_STR(BTM_SECURITY_FAILED_EVT)
    CASE_RETURN_STR(BTM_SECURITY_ABORTED_EVT)
    CASE_RETURN_STR(BTM_READ_LOCAL_OOB_DATA_COMPLETE_EVT)
    CASE_RETURN_STR(BTM_REMOTE_OOB_DATA_REQUEST_EVT)
    CASE_RETURN_STR(BTM_PAIRED_DEVICE_LINK_KEYS_UPDATE_EVT)
    CASE_RETURN_STR(BTM_PAIRED_DEVICE_LINK_KEYS_REQUEST_EVT)
    CASE_RETURN_STR(BTM_LOCAL_IDENTITY_KEYS_UPDATE_EVT)
    CASE_RETURN_STR(BTM_LOCAL_IDENTITY_KEYS_REQUEST_EVT)
    CASE_RETURN_STR(BTM_BLE_SCAN_STATE_CHANGED_EVT)
    CASE_RETURN_STR(BTM_BLE_ADVERT_STATE_CHANGED_EVT)
    CASE_RETURN_STR(BTM_SMP_REMOTE_OOB_DATA_REQUEST_EVT)
    CASE_RETURN_STR(BTM_SMP_SC_REMOTE_OOB_DATA_REQUEST_EVT)
    CASE_RETURN_STR(BTM_SMP_SC_LOCAL_OOB_DATA_NOTIFICATION_EVT)
    CASE_RETURN_STR(BTM_SCO_CONNECTED_EVT)
    CASE_RETURN_STR(BTM_SCO_DISCONNECTED_EVT)
    CASE_RETURN_STR(BTM_SCO_CONNECTION_REQUEST_EVT)
    CASE_RETURN_STR(BTM_SCO_CONNECTION_CHANGE_EVT)
    CASE_RETURN_STR(BTM_BLE_CONNECTION_PARAM_UPDATE)
    CASE_RETURN_STR(BTM_BLE_PHY_UPDATE_EVT)
    CASE_RETURN_STR(BTM_BLE_DATA_LENGTH_UPDATE_EVENT)
  }
  return "UNKNOWN_EVENT";
}
/*-----------------------------------------------------------------------------------------------------


  \param status

  \return const char*
-----------------------------------------------------------------------------------------------------*/
const char* get_bt_gatt_status_name(wiced_bt_gatt_status_t status)
{
  switch ((int)status)
  {
    CASE_RETURN_STR(WICED_BT_GATT_SUCCESS)
    CASE_RETURN_STR(WICED_BT_GATT_INVALID_HANDLE)
    CASE_RETURN_STR(WICED_BT_GATT_READ_NOT_PERMIT)
    CASE_RETURN_STR(WICED_BT_GATT_WRITE_NOT_PERMIT)
    CASE_RETURN_STR(WICED_BT_GATT_INVALID_PDU)
    CASE_RETURN_STR(WICED_BT_GATT_INSUF_AUTHENTICATION)
    CASE_RETURN_STR(WICED_BT_GATT_REQ_NOT_SUPPORTED)
    CASE_RETURN_STR(WICED_BT_GATT_INVALID_OFFSET)
    CASE_RETURN_STR(WICED_BT_GATT_INSUF_AUTHORIZATION)
    CASE_RETURN_STR(WICED_BT_GATT_PREPARE_Q_FULL)
    CASE_RETURN_STR(WICED_BT_GATT_ATTRIBUTE_NOT_FOUND)
    CASE_RETURN_STR(WICED_BT_GATT_NOT_LONG)
    CASE_RETURN_STR(WICED_BT_GATT_INSUF_KEY_SIZE)
    CASE_RETURN_STR(WICED_BT_GATT_INVALID_ATTR_LEN)
    CASE_RETURN_STR(WICED_BT_GATT_ERR_UNLIKELY)
    CASE_RETURN_STR(WICED_BT_GATT_INSUF_ENCRYPTION)
    CASE_RETURN_STR(WICED_BT_GATT_UNSUPPORT_GRP_TYPE)
    CASE_RETURN_STR(WICED_BT_GATT_INSUF_RESOURCE)
    CASE_RETURN_STR(WICED_BT_GATT_ILLEGAL_PARAMETER)
    CASE_RETURN_STR(WICED_BT_GATT_NO_RESOURCES)
    CASE_RETURN_STR(WICED_BT_GATT_INTERNAL_ERROR)
    CASE_RETURN_STR(WICED_BT_GATT_WRONG_STATE)
    CASE_RETURN_STR(WICED_BT_GATT_DB_FULL)
    CASE_RETURN_STR(WICED_BT_GATT_BUSY)
    CASE_RETURN_STR(WICED_BT_GATT_ERROR)
    CASE_RETURN_STR(WICED_BT_GATT_CMD_STARTED)
    CASE_RETURN_STR(WICED_BT_GATT_PENDING)
    CASE_RETURN_STR(WICED_BT_GATT_AUTH_FAIL)
    CASE_RETURN_STR(WICED_BT_GATT_MORE)
    CASE_RETURN_STR(WICED_BT_GATT_INVALID_CFG)
    CASE_RETURN_STR(WICED_BT_GATT_SERVICE_STARTED)
    CASE_RETURN_STR(WICED_BT_GATT_NOT_ENCRYPTED)
    CASE_RETURN_STR(WICED_BT_GATT_CONGESTED)
    CASE_RETURN_STR(WICED_BT_GATT_WRITE_REQ_REJECTED)
    CASE_RETURN_STR(WICED_BT_GATT_CCC_CFG_ERR)
    CASE_RETURN_STR(WICED_BT_GATT_PRC_IN_PROGRESS)
    CASE_RETURN_STR(WICED_BT_GATT_OUT_OF_RANGE)
  }
  return "UNKNOWN_STATUS";
}

/*-----------------------------------------------------------------------------------------------------


  \param event

  \return const char*
-----------------------------------------------------------------------------------------------------*/
const char* get_bt_gatt_evt_name(wiced_bt_gatt_evt_t event)
{
  switch ((int)event)
  {
    CASE_RETURN_STR(GATT_CONNECTION_STATUS_EVT)
    CASE_RETURN_STR(GATT_OPERATION_CPLT_EVT)
    CASE_RETURN_STR(GATT_DISCOVERY_RESULT_EVT)
    CASE_RETURN_STR(GATT_DISCOVERY_CPLT_EVT)
    CASE_RETURN_STR(GATT_ATTRIBUTE_REQUEST_EVT)
    CASE_RETURN_STR(GATT_CONGESTION_EVT)
    CASE_RETURN_STR(GATT_GET_RESPONSE_BUFFER_EVT)
    CASE_RETURN_STR(GATT_APP_BUFFER_TRANSMITTED_EVT)
  }
  return "UNKNOWN_STATUS";
}
/*-----------------------------------------------------------------------------------------------------


  \param reason

  \return const char*
-----------------------------------------------------------------------------------------------------*/
const char* get_bt_gatt_disconn_reason_name(wiced_bt_gatt_disconn_reason_t reason)
{
  switch ((int)reason)
  {
    CASE_RETURN_STR(GATT_CONN_UNKNOWN)
    CASE_RETURN_STR(GATT_CONN_L2C_FAILURE)
    CASE_RETURN_STR(GATT_CONN_TIMEOUT)
    CASE_RETURN_STR(GATT_CONN_TERMINATE_PEER_USER)
    CASE_RETURN_STR(GATT_CONN_TERMINATE_LOCAL_HOST)
    CASE_RETURN_STR(GATT_CONN_FAIL_ESTABLISH)
    CASE_RETURN_STR(GATT_CONN_LMP_TIMEOUT)
    CASE_RETURN_STR(GATT_CONN_CANCEL)
  }
  return "UNKNOWN_REASON";
}

/*-----------------------------------------------------------------------------------------------------


  \param reason

  \return const char*
-----------------------------------------------------------------------------------------------------*/
const char* get_bt_stack_err_name(cybt_result_t res)
{
  switch ((int)res)
  {
    CASE_RETURN_STR(CYBT_SUCCESS                        )
    CASE_RETURN_STR(CYBT_ERR_BADARG                     )
    CASE_RETURN_STR(CYBT_ERR_OUT_OF_MEMORY              )
    CASE_RETURN_STR(CYBT_ERR_TIMEOUT                    )
    CASE_RETURN_STR(CYBT_ERR_HCI_INIT_FAILED            )
    CASE_RETURN_STR(CYBT_ERR_HCI_UNSUPPORTED_IF         )
    CASE_RETURN_STR(CYBT_ERR_HCI_UNSUPPORTED_BAUDRATE   )
    CASE_RETURN_STR(CYBT_ERR_HCI_NOT_INITIALIZE         )
    CASE_RETURN_STR(CYBT_ERR_HCI_WRITE_FAILED           )
    CASE_RETURN_STR(CYBT_ERR_HCI_READ_FAILED            )
    CASE_RETURN_STR(CYBT_ERR_HCI_GET_TX_MUTEX_FAILED    )
    CASE_RETURN_STR(CYBT_ERR_HCI_GET_RX_MUTEX_FAILED    )
    CASE_RETURN_STR(CYBT_ERR_HCI_SET_BAUDRATE_FAILED    )
    CASE_RETURN_STR(CYBT_ERR_HCI_SET_FLOW_CTRL_FAILED   )
    CASE_RETURN_STR(CYBT_ERR_INIT_MEMPOOL_FAILED        )
    CASE_RETURN_STR(CYBT_ERR_INIT_QUEUE_FAILED          )
    CASE_RETURN_STR(CYBT_ERR_CREATE_TASK_FAILED         )
    CASE_RETURN_STR(CYBT_ERR_SEND_QUEUE_FAILED          )
    CASE_RETURN_STR(CYBT_ERR_MEMPOOL_NOT_INITIALIZE     )
    CASE_RETURN_STR(CYBT_ERR_QUEUE_ALMOST_FULL          )
    CASE_RETURN_STR(CYBT_ERR_QUEUE_FULL                 )
    CASE_RETURN_STR(CYBT_ERR_GPIO_POWER_INIT_FAILED     )
    CASE_RETURN_STR(CYBT_ERR_GPIO_DEV_WAKE_INIT_FAILED  )
    CASE_RETURN_STR(CYBT_ERR_GPIO_HOST_WAKE_INIT_FAILED )
    CASE_RETURN_STR(CYBT_ERR_GENERIC                    )
  }
  return "UNKNOWN";
}
