#include "App.h"

#define  IVAR_SIZE        66

#define  SELECTORS_NUM     7

IVAR_TYPE  ivar;


const T_parmenu parmenu[PARMNU_ITEM_NUM]=
{
{ S7V30BOOT_WIFI_STA          , S7V30BOOT_WIFI_STA1         , "WiFi Station Configuration 1", "                    ", -1   }, // 
{ S7V30BOOT_0                 , S7V30BOOT_main              , "Parameters and settings    ", "PARAMETERS          ", -1   }, // Основная категория
{ S7V30BOOT_WIFI_STA          , S7V30BOOT_WIFI_STA2         , "WiFi Station Configuration 2 ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_General           , "General settings           ", "GENERAL_SETTINGS    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_USB_Interface     , "USB Interface settings     ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_Network           , "Network settings           ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_BLE               , "Bluetooth settings         ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_WIFI_STA          , "WiFi Station interface settings", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_WIFI_AP           , "WiFi Access Point interface settings", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_Telnet            , "Telnet settings            ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_WEB               , "HTTP server settings       ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_FTP_server        , "FTP server settings        ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_MQTT              , "MQTT settings              ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_SNTP              , "Net time protocol setting  ", "                    ", -1   }, // 
{ S7V30BOOT_main              , S7V30BOOT_FreeMaster        , "FreeMaster communication settings", "                    ", 0    }, // 
{ S7V30BOOT_main              , S7V30BOOT_Audio             , "Audio settings             ", "                    ", 0    }, // 
};


static const T_NV_parameters arr_ivar[IVAR_SIZE]=
{
// N: 0
  {
    "audio_volume",
    "Volume (0...10)",
    "-",
    (void*)&ivar.audio_volume,
    tint32u,
    8,
    0,
    10,
    0,
    S7V30BOOT_Audio,
    "",
    "%d",
    0,
    sizeof(ivar.audio_volume),
    0,
    0,
  },
// N: 1
  {
    "en_ble",
    "Enable Bluetooth",
    "-",
    (void*)&ivar.en_ble,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_BLE,
    "",
    "%d",
    0,
    sizeof(ivar.en_ble),
    0,
    1,
  },
// N: 2
  {
    "bt_device_name",
    "Bluetooth Classic device name",
    "-",
    (void*)&ivar.bt_device_name,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_BLE,
    "BT_S7V30",
    "%s",
    0,
    sizeof(ivar.bt_device_name)-1,
    1,
    0,
  },
// N: 3
  {
    "ble_device_name",
    "Bluetooth LE device name",
    "-",
    (void*)&ivar.ble_device_name,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_BLE,
    "BLE_S7V30",
    "%s",
    0,
    sizeof(ivar.ble_device_name)-1,
    2,
    0,
  },
// N: 4
  {
    "en_freemaster",
    "Enable FreeMaster protocol",
    "-",
    (void*)&ivar.en_freemaster,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_FreeMaster,
    "",
    "%d",
    0,
    sizeof(ivar.en_freemaster),
    0,
    1,
  },
// N: 5
  {
    "en_log_to_freemaster",
    "Enable logging to FreeMaster pipe",
    "-",
    (void*)&ivar.en_log_to_freemaster,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_FreeMaster,
    "",
    "%d",
    0,
    sizeof(ivar.en_log_to_freemaster),
    1,
    1,
  },
// N: 6
  {
    "enable_ftp_server",
    "Enable FTP server",
    "-",
    (void*)&ivar.enable_ftp_server,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_FTP_server,
    "",
    "%d",
    0,
    sizeof(ivar.enable_ftp_server),
    1,
    1,
  },
// N: 7
  {
    "ftp_serv_login",
    "Login",
    "-",
    (void*)&ivar.ftp_serv_login,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_FTP_server,
    "ftp_login",
    "%s",
    0,
    sizeof(ivar.ftp_serv_login)-1,
    2,
    0,
  },
// N: 8
  {
    "ftp_serv_password",
    "Password ",
    "-",
    (void*)&ivar.ftp_serv_password,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_FTP_server,
    "ftp_pass",
    "%s",
    0,
    sizeof(ivar.ftp_serv_password)-1,
    3,
    0,
  },
// N: 9
  {
    "product_name",
    "Product  name",
    "SYSNAM",
    (void*)&ivar.product_name,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_General,
    "S7V30",
    "%s",
    0,
    sizeof(ivar.product_name)-1,
    1,
    0,
  },
// N: 10
  {
    "software_version",
    "Software version",
    "-",
    (void*)&ivar.software_version,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_General,
    "S7V30",
    "%s",
    0,
    sizeof(ivar.software_version)-1,
    2,
    0,
  },
// N: 11
  {
    "hardware_version",
    "Hardware version",
    "-",
    (void*)&ivar.hardware_version,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_General,
    "S7V30 ",
    "%s",
    0,
    sizeof(ivar.hardware_version)-1,
    3,
    0,
  },
// N: 12
  {
    "manuf_date",
    "Manufacturing date",
    "FRMVER",
    (void*)&ivar.manuf_date,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_General,
    "2023 04 25",
    "%s",
    0,
    sizeof(ivar.manuf_date)-1,
    4,
    0,
  },
// N: 13
  {
    "en_wifi_module",
    "Enable  Wi-Fi Bluetooth module ",
    "-",
    (void*)&ivar.en_wifi_module,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_General,
    "",
    "%d",
    0,
    sizeof(ivar.en_wifi_module),
    5,
    1,
  },
// N: 14
  {
    "en_log_to_file",
    "Enable logging to file",
    "-",
    (void*)&ivar.en_log_to_file,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_General,
    "",
    "%d",
    0,
    sizeof(ivar.en_log_to_file),
    6,
    1,
  },
// N: 15
  {
    "en_compress_settins",
    "Enable compress settings file",
    "-",
    (void*)&ivar.en_compress_settins,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_General,
    "",
    "%d",
    0,
    sizeof(ivar.en_compress_settins),
    7,
    1,
  },
// N: 16
  {
    "en_formating_settings",
    "Enable formating in  settings file",
    "-",
    (void*)&ivar.en_formated_settings,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_General,
    "",
    "%d",
    0,
    sizeof(ivar.en_formated_settings),
    8,
    1,
  },
// N: 17
  {
    "disable_jump_to_applacation",
    "Disable jump to application",
    "-",
    (void*)&ivar.disable_jump_to_applacation,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_General,
    "",
    "%d",
    0,
    sizeof(ivar.disable_jump_to_applacation),
    9,
    1,
  },
// N: 18
  {
    "en_auto_protection",
    "Enable auto protection",
    "-",
    (void*)&ivar.en_auto_protection,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_General,
    "",
    "%d",
    0,
    sizeof(ivar.en_auto_protection),
    10,
    1,
  },
// N: 19
  {
    "sd_card_password",
    "SD card password",
    "-",
    (void*)&ivar.sd_card_password,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_General,
    "1234",
    "%s",
    0,
    sizeof(ivar.sd_card_password)-1,
    11,
    0,
  },
// N: 20
  {
    "mqtt_enable",
    "Enable MQTT client ",
    "-",
    (void*)&ivar.mqtt_enable,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_MQTT,
    "",
    "%d",
    0,
    sizeof(ivar.mqtt_enable),
    1,
    1,
  },
// N: 21
  {
    "mqtt_client_id",
    "Client ID",
    "-",
    (void*)&ivar.mqtt_client_id,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_MQTT,
    "Client1",
    "%s",
    0,
    sizeof(ivar.mqtt_client_id)-1,
    2,
    0,
  },
// N: 22
  {
    "mqtt_server_ip",
    "MQTT server IP address",
    "-",
    (void*)&ivar.mqtt_server_ip,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_MQTT,
    "192.168.3.2",
    "%s",
    0,
    sizeof(ivar.mqtt_server_ip)-1,
    3,
    0,
  },
// N: 23
  {
    "mqtt_server_port",
    "MQTT server port number",
    "-",
    (void*)&ivar.mqtt_server_port,
    tint32u,
    1883,
    0,
    65535,
    0,
    S7V30BOOT_MQTT,
    "",
    "%d",
    0,
    sizeof(ivar.mqtt_server_port),
    4,
    0,
  },
// N: 24
  {
    "mqtt_user_name",
    "User name",
    "-",
    (void*)&ivar.mqtt_user_name,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_MQTT,
    "user",
    "%s",
    0,
    sizeof(ivar.mqtt_user_name)-1,
    5,
    0,
  },
// N: 25
  {
    "mqtt_password",
    "User password",
    "-",
    (void*)&ivar.mqtt_password,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_MQTT,
    "pass",
    "%s",
    0,
    sizeof(ivar.mqtt_password)-1,
    6,
    0,
  },
// N: 26
  {
    "this_host_name",
    "This device host name",
    "HOSTNAM",
    (void*)&ivar.this_host_name,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_Network,
    "S7V30",
    "%s",
    0,
    sizeof(ivar.this_host_name)-1,
    0,
    0,
  },
// N: 27
  {
    "en_net_log",
    "Enable log",
    "-",
    (void*)&ivar.en_net_log,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_Network,
    "",
    "%d",
    0,
    sizeof(ivar.en_net_log),
    1,
    1,
  },
// N: 28
  {
    "en_sntp",
    "Enable SNTP client",
    "-",
    (void*)&ivar.en_sntp,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_SNTP,
    "",
    "%d",
    0,
    sizeof(ivar.en_sntp),
    1,
    1,
  },
// N: 29
  {
    "en_sntp_time_receiving",
    "Allow to receive time from time servers",
    "-",
    (void*)&ivar.en_sntp_time_receiving,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_SNTP,
    "",
    "%d",
    0,
    sizeof(ivar.en_sntp_time_receiving),
    2,
    1,
  },
// N: 30
  {
    "utc_offset",
    "UTC offset (difference in hours +-)",
    "-",
    (void*)&ivar.utc_offset,
    tfloat,
    3.00,
    -12.00,
    12.00,
    0,
    S7V30BOOT_SNTP,
    "",
    "%0.0f",
    0,
    sizeof(ivar.utc_offset),
    3,
    0,
  },
// N: 31
  {
    "time_server_1",
    "Time server 1 URL",
    "-",
    (void*)&ivar.time_server_1,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_SNTP,
    "pool.ntp.org",
    "%s",
    0,
    sizeof(ivar.time_server_1)-1,
    4,
    0,
  },
// N: 32
  {
    "time_server_2",
    "Time server 2 URL",
    "-",
    (void*)&ivar.time_server_2,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_SNTP,
    "129.6.15.28",
    "%s",
    0,
    sizeof(ivar.time_server_2)-1,
    5,
    0,
  },
// N: 33
  {
    "time_server_3",
    "Time serber 3 URL",
    "-",
    (void*)&ivar.time_server_3,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_SNTP,
    "time.nist.gov",
    "%s",
    0,
    sizeof(ivar.time_server_3)-1,
    6,
    0,
  },
// N: 34
  {
    "sntp_poll_interval",
    "Poll interval (s)",
    "-",
    (void*)&ivar.sntp_poll_interval,
    tint32u,
    120,
    1,
    1000000,
    0,
    S7V30BOOT_SNTP,
    "",
    "%d",
    0,
    sizeof(ivar.sntp_poll_interval),
    7,
    0,
  },
// N: 35
  {
    "en_telnet",
    "Enable Telnet",
    "-",
    (void*)&ivar.en_telnet,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_Telnet,
    "",
    "%d",
    0,
    sizeof(ivar.en_telnet),
    0,
    1,
  },
// N: 36
  {
    "usb_mode",
    "USB interface mode",
    "USBIMOD",
    (void*)&ivar.usb_mode,
    tint32u,
    1,
    0,
    7,
    0,
    S7V30BOOT_USB_Interface,
    "",
    "%d",
    0,
    sizeof(ivar.usb_mode),
    1,
    4,
  },
// N: 37
  {
    "usd_dev_interface",
    "USB device interface (HS/FS)",
    "-",
    (void*)&ivar.usd_dev_interface,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_USB_Interface,
    "",
    "%d",
    0,
    sizeof(ivar.usd_dev_interface),
    2,
    6,
  },
// N: 38
  {
    "en_rndis_dhcp_server",
    "Enable DHCP server on RNDIS interface ",
    "RNDSCFG",
    (void*)&ivar.en_rndis_dhcp_server,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_USB_Interface,
    "",
    "%d",
    0,
    sizeof(ivar.en_rndis_dhcp_server),
    3,
    1,
  },
// N: 39
  {
    "en_ecm_host_dhcp_client",
    "Enable DHCP client on ECM host interface ",
    "-",
    (void*)&ivar.en_ecm_host_dhcp_client,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_USB_Interface,
    "",
    "%d",
    0,
    sizeof(ivar.en_ecm_host_dhcp_client),
    4,
    1,
  },
// N: 40
  {
    "usb_default_ip_addr",
    "Default IP address",
    "DEFIPAD",
    (void*)&ivar.usb_default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_USB_Interface,
    "192.168.13.1",
    "%s",
    0,
    sizeof(ivar.usb_default_ip_addr)-1,
    5,
    2,
  },
// N: 41
  {
    "usb_default_net_mask",
    "Default network mask ",
    "DEFNTMS",
    (void*)&ivar.usb_default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_USB_Interface,
    "255.255.255.0",
    "%s",
    0,
    sizeof(ivar.usb_default_net_mask)-1,
    6,
    2,
  },
// N: 42
  {
    "enable_HTTP_server",
    "Enable HTTP server",
    "-",
    (void*)&ivar.enable_HTTP_server,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_WEB,
    "",
    "%d",
    0,
    sizeof(ivar.enable_HTTP_server),
    0,
    1,
  },
// N: 43
  {
    "enable_HTTPS",
    "Enable TLS",
    "-",
    (void*)&ivar.enable_HTTPS,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_WEB,
    "",
    "%d",
    0,
    sizeof(ivar.enable_HTTPS),
    1,
    1,
  },
// N: 44
  {
    "HTTP_server_password",
    "HTTP server password",
    "-",
    (void*)&ivar.HTTP_server_password,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_WEB,
    "123456789",
    "%d",
    0,
    sizeof(ivar.HTTP_server_password)-1,
    2,
    0,
  },
// N: 45
  {
    "en_wifi_ap",
    "Enable Acces Point mode",
    "-",
    (void*)&ivar.en_wifi_ap,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_WIFI_AP,
    "",
    "%d",
    0,
    sizeof(ivar.en_wifi_ap),
    0,
    1,
  },
// N: 46
  {
    "wifi_ap_ssid",
    "Access Point SSID",
    "-",
    (void*)&ivar.wifi_ap_ssid,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_AP,
    "S7V30",
    "%s",
    0,
    sizeof(ivar.wifi_ap_ssid)-1,
    1,
    0,
  },
// N: 47
  {
    "wifi_ap_key",
    "Access Point password (>=8 symbols)",
    "-",
    (void*)&ivar.wifi_ap_key,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_WIFI_AP,
    "12345678",
    "%s",
    0,
    sizeof(ivar.wifi_ap_key)-1,
    2,
    0,
  },
// N: 48
  {
    "ap_default_ip_addr",
    "Default IP address",
    "-",
    (void*)&ivar.ap_default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_AP,
    "192.168.10.1",
    "%s",
    0,
    sizeof(ivar.ap_default_ip_addr)-1,
    3,
    0,
  },
// N: 49
  {
    "ap_default_net_mask",
    "Default network mask ",
    "-",
    (void*)&ivar.ap_default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_AP,
    "255.255.255.0",
    "%s",
    0,
    sizeof(ivar.ap_default_net_mask)-1,
    4,
    0,
  },
// N: 50
  {
    "ap_en_dhcp_server",
    "Enable DHCP server",
    "-",
    (void*)&ivar.ap_en_dhcp_server,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_WIFI_AP,
    "",
    "%d",
    0,
    sizeof(ivar.ap_en_dhcp_server),
    5,
    1,
  },
// N: 51
  {
    "wifi_ap_channel",
    "WIFI channell",
    "-",
    (void*)&ivar.wifi_ap_channel,
    tint8u,
    1,
    0,
    255,
    0,
    S7V30BOOT_WIFI_AP,
    "",
    "%d",
    0,
    sizeof(ivar.wifi_ap_channel),
    6,
    0,
  },
// N: 52
  {
    "wifi_sta_cfg1_en",
    "Enable configuration",
    "-",
    (void*)&ivar.wifi_sta_cfg1_en,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_WIFI_STA1,
    "",
    "%d",
    0,
    sizeof(ivar.wifi_sta_cfg1_en),
    0,
    1,
  },
// N: 53
  {
    "wifi_sta_cfg1_pass",
    "Password ",
    "-",
    (void*)&ivar.wifi_sta_cfg1_pass,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_WIFI_STA1,
    "wifi_pass",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg1_pass)-1,
    1,
    0,
  },
// N: 54
  {
    "wifi_sta_cfg1_ssid",
    "SSID",
    "-",
    (void*)&ivar.wifi_sta_cfg1_ssid,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA1,
    "wifi_login",
    "%d",
    0,
    sizeof(ivar.wifi_sta_cfg1_ssid)-1,
    2,
    0,
  },
// N: 55
  {
    "wifi_sta_cfg1_en_dhcp",
    "Enable DHCP client",
    "-",
    (void*)&ivar.wifi_sta_cfg1_en_dhcp,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_WIFI_STA1,
    "",
    "%d",
    0,
    sizeof(ivar.wifi_sta_cfg1_en_dhcp),
    3,
    1,
  },
// N: 56
  {
    "wifi_sta_cfg1_default_ip_addr",
    "Default IP address",
    "-",
    (void*)&ivar.wifi_sta_cfg1_default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA1,
    "192.168.11.1",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg1_default_ip_addr)-1,
    4,
    2,
  },
// N: 57
  {
    "wifi_sta_cfg1_default_net_mask",
    "Default network mask ",
    "-",
    (void*)&ivar.wifi_sta_cfg1_default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA1,
    "255.255.255.0",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg1_default_net_mask)-1,
    5,
    2,
  },
// N: 58
  {
    "wifi_sta_cfg1_default_gate_addr",
    "Default gateway address",
    "-",
    (void*)&ivar.wifi_sta_cfg1_default_gate_addr,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA1,
    "192.168.11.1",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg1_default_gate_addr)-1,
    6,
    2,
  },
// N: 59
  {
    "wifi_sta_cfg2_en",
    "Enable configuration",
    "-",
    (void*)&ivar.wifi_sta_cfg2_en,
    tint8u,
    0,
    0,
    1,
    0,
    S7V30BOOT_WIFI_STA2,
    "",
    "%d",
    0,
    sizeof(ivar.wifi_sta_cfg2_en),
    0,
    1,
  },
// N: 60
  {
    "wifi_sta_cfg2_pass",
    "Password ",
    "-",
    (void*)&ivar.wifi_sta_cfg2_pass,
    tstring,
    0,
    0,
    0,
    4,
    S7V30BOOT_WIFI_STA2,
    "wifi_pass",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg2_pass)-1,
    1,
    0,
  },
// N: 61
  {
    "wifi_sta_cfg2_ssid",
    "SSID",
    "-",
    (void*)&ivar.wifi_sta_cfg2_ssid,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA2,
    "wifi_login",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg2_ssid)-1,
    2,
    0,
  },
// N: 62
  {
    "wifi_sta_cfg2_en_dhcp",
    "Enable DHCP client",
    "-",
    (void*)&ivar.wifi_sta_cfg2_en_dhcp,
    tint8u,
    1,
    0,
    1,
    0,
    S7V30BOOT_WIFI_STA2,
    "",
    "%d",
    0,
    sizeof(ivar.wifi_sta_cfg2_en_dhcp),
    3,
    1,
  },
// N: 63
  {
    "wifi_sta_cfg2_default_ip_addr",
    "Default IP address",
    "-",
    (void*)&ivar.wifi_sta_cfg2_default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA2,
    "192.168.12.1",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg2_default_ip_addr)-1,
    4,
    0,
  },
// N: 64
  {
    "wifi_sta_cfg2_default_net_mask",
    "Default network mask ",
    "-",
    (void*)&ivar.wifi_sta_cfg2_default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA2,
    "255.255.255.0",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg2_default_net_mask)-1,
    5,
    0,
  },
// N: 65
  {
    "wifi_sta_cfg2_default_gate_addr",
    "Default gateway address",
    "-",
    (void*)&ivar.wifi_sta_cfg2_default_gate_addr,
    tstring,
    0,
    0,
    0,
    0,
    S7V30BOOT_WIFI_STA2,
    "192.168.12.1",
    "%s",
    0,
    sizeof(ivar.wifi_sta_cfg2_default_gate_addr)-1,
    6,
    0,
  },
};
 
 
// Selector description:  Выбор между Yes и No
static const T_selector_items selector_1[2] = 
{
  { 0 , "No                                          " , 0},
  { 1 , "Yes                                         " , 1},
};
 
// Selector description:  LED mode
static const T_selector_items selector_3[2] = 
{
  { 0 , "Always OFF                                  " , -1},
  { 1 , "Normal work                                 " , -1},
};
 
// Selector description:  USB mode
static const T_selector_items selector_4[8] = 
{
  { 0 , "None                                        " , -1},
  { 1 , "VCOM port                                   " , -1},
  { 2 , "Mass storage                                " , -1},
  { 3 , "VCOM and Mass storage                       " , -1},
  { 5 , "VCOM and FreeMaster port                    " , -1},
  { 6 , "RNDIS                                       " , -1},
  { 7 , "Host ECM                                    " , -1},
  { 4 , "VCOM and VCOM                               " , -1},
};
 
// Selector description:  IP address assignment method
static const T_selector_items selector_5[2] = 
{
  { 0 , "Static adress                               " , -1},
  { 1 , "DHCP server                                 " , -1},
};
 
// Selector description:  Выбор интерфейса для работы USB device
static const T_selector_items selector_6[2] = 
{
  { 0 , "High speed interface                        " , -1},
  { 1 , "Full speed interface                        " , -1},
};
 
static const T_selectors_list selectors_list[SELECTORS_NUM] = 
{
  {"string"                      , 0    , 0             },
  {"binary"                      , 2    , selector_1    },
  {"ip_addr"                     , 0    , 0             },
  {"leds_mode"                   , 2    , selector_3    },
  {"usb_mode"                    , 8    , selector_4    },
  {"IP_address_assignment_method", 2    , selector_5    },
  {"usb_dev_interface"           , 2    , selector_6    },
};
 
const T_NV_parameters_instance ivar_inst =
{
  IVAR_SIZE,
  arr_ivar,
  PARMNU_ITEM_NUM,
  parmenu,
  SELECTORS_NUM,
  selectors_list
};
