/***************************************************************************//**
* File Name: cycfg_bt_settings.h
*
* Description:
* Bluetooth Configurator configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
********************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_BT_SETTINGS_H)
#define CYCFG_BT_SETTINGS_H

#include "wiced_bt_cfg.h"
#include "wiced_bt_ble.h"

extern wiced_bt_cfg_ble_scan_settings_t cy_bt_cfg_scan_settings;
extern wiced_bt_cfg_ble_advert_settings_t cy_bt_cfg_adv_settings;
extern wiced_bt_cfg_ble_t cy_bt_cfg_ble;
extern wiced_bt_cfg_gatt_t cy_bt_cfg_gatt;
extern wiced_bt_cfg_br_t cy_bt_cfg_br;
extern wiced_bt_cfg_settings_t cy_bt_cfg_settings;
extern const wiced_bt_cfg_l2cap_application_t cy_bt_cfg_l2cap;

/* BR/EDR specific configuration */
#define CY_BT_BR_MAX_CONNECTIONS                              1
#define CY_BT_BR_MAX_RX_PDU_SIZE                              1024
#define CY_BT_BR_AV_DT_MAX_CONNECTIONS                        0
#define CY_BT_BR_AV_DT_MAX_ENDPOINTS                          0
#define CY_BT_BR_AV_RC_MAX_CONNECTIONS                        0
#define CY_BT_BR_RFCOMM_MAX_CONNECTIONS                       1
#define CY_BT_BR_RFCOMM_MAX_PORTS                             1

/* Isochronous connection configuration */
#define CY_BT_ISOC_MAX_SDU_SIZE                               0
#define CY_BT_ISOC_MAX_AUDIO_CHANNELS                         0
#define CY_BT_ISOC_MAX_CIS_CONNECTIONS                        0
#define CY_BT_ISOC_MAX_CIG_CONNECTIONS                        0
#define CY_BT_ISOC_MAX_BUFS_PER_CIS                           0
#define CY_BT_ISOC_MAX_BIG_CONNECTIONS                        0

#endif /* CYCFG_BT_SETTINGS_H */

/* [] END OF FILE */
