/***************************************************************************//**
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
********************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"

/* Device address */
wiced_bt_device_address_t cy_bt_device_address = {0x00, 0xA0, 0x50, 0x41, 0xA9, 0x98};

const uint8_t cy_bt_adv_packet_elem_0[1] = { 0x06 };
const uint8_t cy_bt_adv_packet_elem_1[5] = { 0x53, 0x37, 0x56, 0x33, 0x30 };
wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[] = 
{
    /* Flags */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_FLAG, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_0, 
    },
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 5, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_1, 
    },
};
const uint8_t cy_bt_scan_resp_packet_elem_0[5] = { 0x53, 0x37, 0x56, 0x33, 0x30 };
const uint8_t cy_bt_scan_resp_packet_elem_1[1] = { 0x0C };
const uint8_t cy_bt_scan_resp_packet_elem_2[2] = { 0x00, 0x00 };
const uint8_t cy_bt_scan_resp_packet_elem_3[2] = { 0x20, 0x00 };
wiced_bt_ble_advert_elem_t cy_bt_scan_resp_packet_data[] = 
{
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 5, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_0, 
    },
    /* TX Power Level  */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_TX_POWER, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_1, 
    },
    /* Appearance */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_APPEARANCE, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_2, 
    },
    /* Advertising Interval */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_ADVERT_INTERVAL, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_3, 
    },
};
