/***************************************************************************//**
* File Name: cycfg_sdp_db.h
*
* Description:
* Definitions for constants used in the device's SDP database.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
********************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_SDP_DB_H)
#define CYCFG_SDP_DB_H

#include "stdint.h"

/* SDP Record for Device ID */
#define HDLR_DEVICE_ID    0x010001
/* SDP Record for Serial Port */
#define HDLR_SERIAL_PORT    0x010002


// External definitions
extern const uint8_t  sdp_database[];
extern const uint16_t sdp_database_len;

#endif /* CYCFG_SDP_DB_H */
