/******************************************************************************
* File Name: cycfg_gatt_db.c
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
*******************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/******************************************************************************
* GATT server definitions
******************************************************************************/

const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GAP,
            __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_DEVICE_NAME,
                HDLC_GAP_DEVICE_NAME_VALUE,
                __UUID_CHARACTERISTIC_DEVICE_NAME,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_APPEARANCE,
                HDLC_GAP_APPEARANCE_VALUE,
                __UUID_CHARACTERISTIC_APPEARANCE,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GATT,
            __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Custom Service */
    PRIMARY_SERVICE_UUID128 (
            HDLS_CUSTOM_SERVICE,
            __UUID_SERVICE_CUSTOM_SERVICE),
        /* Characteristic: WIFI SSID */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_CUSTOM_SERVICE_WIFI_SSID,
                HDLC_CUSTOM_SERVICE_WIFI_SSID_VALUE,
                __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_SSID,
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_WRITE,
                GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE | GATTDB_PERM_RELIABLE_WRITE),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_CUSTOM_SERVICE_WIFI_SSID_CHAR_USER_DESCRIPTION,
                    __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION,
                    GATTDB_PERM_READABLE),
        /* Characteristic: WIFI PASSWORD */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_CUSTOM_SERVICE_WIFI_PASSWORD,
                HDLC_CUSTOM_SERVICE_WIFI_PASSWORD_VALUE,
                __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_PASSWORD,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
                GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD | GATTDB_PERM_AUTH_WRITABLE),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_CUSTOM_SERVICE_WIFI_PASSWORD_CHAR_USER_DESCRIPTION,
                    __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION,
                    GATTDB_PERM_READABLE),
        /* Characteristic: WIFI NETWORKS */
        CHARACTERISTIC_UUID128 (
                HDLC_CUSTOM_SERVICE_WIFI_NETWORKS,
                HDLC_CUSTOM_SERVICE_WIFI_NETWORKS_VALUE,
                __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_NETWORKS,
                GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_NONE),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_CUSTOM_SERVICE_WIFI_NETWORKS_CHAR_USER_DESCRIPTION,
                    __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION,
                    GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_CUSTOM_SERVICE_WIFI_NETWORKS_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
        /* Characteristic: WIFI CONTROL */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_CUSTOM_SERVICE_WIFI_CONTROL,
                HDLC_CUSTOM_SERVICE_WIFI_CONTROL_VALUE,
                __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_CONTROL,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_WRITE_NO_RESPONSE | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_WRITE_REQ | GATTDB_PERM_WRITE_CMD),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_CUSTOM_SERVICE_WIFI_CONTROL_CHAR_USER_DESCRIPTION,
                    __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION,
                    GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_CUSTOM_SERVICE_WIFI_CONTROL_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/******************************************************************************
* GATT Initial Value Arrays
******************************************************************************/
 
uint8_t app_gap_device_name[] = {'S', '7', 'V', '3', '0', '\0',};
uint8_t app_gap_appearance[] = {0x00, 0x00,};
uint8_t app_custom_service_wifi_ssid[] = {'-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
    '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
    '-', '-',};
uint8_t app_custom_service_wifi_ssid_char_user_description[] = {'S', 'S', 'I', 'D',};
uint8_t app_custom_service_wifi_password[] = {'-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
    '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
    '-', '-', '-',};
uint8_t app_custom_service_wifi_password_char_user_description[] = {'P', 'a', 's', 's', 'w',
    'o', 'r', 'd',};
uint8_t app_custom_service_wifi_networks[] = {'-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
    '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
    '-', '-', '-',};
uint8_t app_custom_service_wifi_networks_char_user_description[] = {'W', 'i', 'F', 'i', ' ',
    'N', 'e', 't', 'w', 'o', 'r', 'k', 's',};
uint8_t app_custom_service_wifi_networks_client_char_config[] = {0x00, 0x00,};
uint8_t app_custom_service_wifi_control[] = {0x00,};
uint8_t app_custom_service_wifi_control_char_user_description[] = {'W', 'i', 'F', 'i', ' ', 'C',
    'o', 'n', 't', 'r', 'o', 'l',};
uint8_t app_custom_service_wifi_control_client_char_config[] = {0x00, 0x00,};
 
/******************************************************************************
* GATT Lookup Table
******************************************************************************/
 
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    {
        HDLC_GAP_DEVICE_NAME_VALUE,                              /* attribute handle */
        MAX_LEN_GAP_DEVICE_NAME,                                 /* maxlen */
        5,                                                       /* curlen */
        app_gap_device_name,                                     /* attribute data */
    },
    {
        HDLC_GAP_APPEARANCE_VALUE,                               /* attribute handle */
        MAX_LEN_GAP_APPEARANCE,                                  /* maxlen */
        2,                                                       /* curlen */
        app_gap_appearance,                                      /* attribute data */
    },
    {
        HDLC_CUSTOM_SERVICE_WIFI_SSID_VALUE,                     /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_SSID,                        /* maxlen */
        32,                                                      /* curlen */
        app_custom_service_wifi_ssid,                            /* attribute data */
    },
    {
        HDLD_CUSTOM_SERVICE_WIFI_SSID_CHAR_USER_DESCRIPTION,     /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_SSID_CHAR_USER_DESCRIPTION,  /* maxlen */
        4,                                                       /* curlen */
        app_custom_service_wifi_ssid_char_user_description,      /* attribute data */
    },
    {
        HDLC_CUSTOM_SERVICE_WIFI_PASSWORD_VALUE,                 /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_PASSWORD,                    /* maxlen */
        32,                                                      /* curlen */
        app_custom_service_wifi_password,                        /* attribute data */
    },
    {
        HDLD_CUSTOM_SERVICE_WIFI_PASSWORD_CHAR_USER_DESCRIPTION, /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_PASSWORD_CHAR_USER_DESCRIPTION,/* maxlen */
        8,                                                       /* curlen */
        app_custom_service_wifi_password_char_user_description,  /* attribute data */
    },
    {
        HDLC_CUSTOM_SERVICE_WIFI_NETWORKS_VALUE,                 /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_NETWORKS,                    /* maxlen */
        32,                                                      /* curlen */
        app_custom_service_wifi_networks,                        /* attribute data */
    },
    {
        HDLD_CUSTOM_SERVICE_WIFI_NETWORKS_CHAR_USER_DESCRIPTION, /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_NETWORKS_CHAR_USER_DESCRIPTION,/* maxlen */
        13,                                                      /* curlen */
        app_custom_service_wifi_networks_char_user_description,  /* attribute data */
    },
    {
        HDLD_CUSTOM_SERVICE_WIFI_NETWORKS_CLIENT_CHAR_CONFIG,    /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_NETWORKS_CLIENT_CHAR_CONFIG, /* maxlen */
        2,                                                       /* curlen */
        app_custom_service_wifi_networks_client_char_config,     /* attribute data */
    },
    {
        HDLC_CUSTOM_SERVICE_WIFI_CONTROL_VALUE,                  /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_CONTROL,                     /* maxlen */
        1,                                                       /* curlen */
        app_custom_service_wifi_control,                         /* attribute data */
    },
    {
        HDLD_CUSTOM_SERVICE_WIFI_CONTROL_CHAR_USER_DESCRIPTION,  /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_CONTROL_CHAR_USER_DESCRIPTION,/* maxlen */
        12,                                                      /* curlen */
        app_custom_service_wifi_control_char_user_description,   /* attribute data */
    },
    {
        HDLD_CUSTOM_SERVICE_WIFI_CONTROL_CLIENT_CHAR_CONFIG,     /* attribute handle */
        MAX_LEN_CUSTOM_SERVICE_WIFI_CONTROL_CLIENT_CHAR_CONFIG,  /* maxlen */
        2,                                                       /* curlen */
        app_custom_service_wifi_control_client_char_config,      /* attribute data */
    },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = 
    (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = 5;
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_custom_service_wifi_ssid_len = (sizeof(app_custom_service_wifi_ssid));
const uint16_t app_custom_service_wifi_ssid_char_user_description_len =
    (sizeof(app_custom_service_wifi_ssid_char_user_description));
const uint16_t app_custom_service_wifi_password_len =
    (sizeof(app_custom_service_wifi_password));
const uint16_t app_custom_service_wifi_password_char_user_description_len =
    (sizeof(app_custom_service_wifi_password_char_user_description));
const uint16_t app_custom_service_wifi_networks_len =
    (sizeof(app_custom_service_wifi_networks));
const uint16_t app_custom_service_wifi_networks_char_user_description_len =
    (sizeof(app_custom_service_wifi_networks_char_user_description));
const uint16_t app_custom_service_wifi_networks_client_char_config_len =
    (sizeof(app_custom_service_wifi_networks_client_char_config));
const uint16_t app_custom_service_wifi_control_len = (sizeof(app_custom_service_wifi_control));
const uint16_t app_custom_service_wifi_control_char_user_description_len =
    (sizeof(app_custom_service_wifi_control_char_user_description));
const uint16_t app_custom_service_wifi_control_client_char_config_len =
    (sizeof(app_custom_service_wifi_control_client_char_config));
